### ISSUE TITLE
Show Error

### ISSUE THREAD

**Issue by serayudigital** [harrison-broadbent/gsc-auto-index-script#3]
script.rb:33:in `get_all_pages_from_sitemap': undefined method `map' for nil:Nil
Class (NoMethodError)

  links = data["url"].map { |url| url["loc"][0] }
                     ^^^^
        from script.rb:100:in `<main>'

**Comment by theodufort** [comment]
> script.rb:33:in `get_all_pages_from_sitemap': undefined method `map' for nil:Nil Class (NoMethodError)
> 
> links = data["url"].map { |url| url["loc"][0] } ^^^^ from script.rb:100:in `
> 
> '

Probably means your sitemap is empty.
